---
- name: Run Reverse Proxy HTTPD Container
  docker_container:
    name: httpd-1
    image: crispychicken02/devops-httpd:1.0
    networks:
      - name: app-network
    ports:
      - "80:80"
    env:
      SIMPLEAPI_HOST: "tp-api"
    restart_policy: always
    state: started
