---
- name: Run Reverse Proxy HTTPD Container
  docker_container:
    name: httpd-1
    image: "{{ dockerhub_username }}/tp-devops-httpd:latest"
    pull: true
    recreate: true
    networks:
      - name: app-network
    ports:
      - "80:80"
    restart_policy: always
    state: started
