---
- name: Run Database Container
  docker_container:
    name: database-1
    image: crispychicken02/devops-database:1.0
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    restart_policy: always
    state: started
