---
- name: Run Database Container
  docker_container:
    name: database-1
    image: "{{ dockerhub_username }}/tp-devops-database:latest"
    pull: true
    recreate: true
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    restart_policy: always
    state: started
